spring:
  application:
    name: shopping-cart

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:native}

  datasource:
    initialization-mode: always
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/shopping_cart_db
    username: ${DB_USER:shopping_cart}
    password: ${DB_PASSWORD:shopping_cart}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

  cloud:
    config:
      server:
        native:
          searchLocations:
            - classpath:config/commerce/{application}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/

server:
  port: 0