spring:
  datasource:
    initialization-mode: always
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/shopping_cart_db
    username: ${DB_USER:shopping_cart}
    password: ${DB_PASSWORD:shopping_cart}

  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true