spring:
  datasource:
    initialization-mode: always
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/warehouse_db
    username: ${DB_USER:warehouse}
    password: ${DB_PASSWORD:warehouse}

  jpa:
    open-in-view: false