spring:
  application:
    name: aggregator

  main:
    web-application-type: none

  config:
    import: "configserver:"

  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 10
        initial-interval: 500
        max-interval: 6000
        multiplier: 1.5
